name: Generate Gallery

on:
  push:
    branches:
      - main
    paths:
      - 'fotos-web/**'

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate HTML for gallery
        id: generate
        run: |
          # Use 'find' para listar los archivos de imagen de forma fiable
          # y evitar problemas con archivos ocultos o nombres raros
          find fotos-web -maxdepth 1 -type f -name "*.jpg" -o -name "*.png" -o -name "*.gif" > file_list.txt
          
          # Comprueba si hay archivos antes de crear el HTML
          if [ -s file_list.txt ]; then
              while read filename
              do
                  image_name=$(basename "$filename")
                  echo "<img src='https://raw.githubusercontent.com/${{ github.repository }}/main/$filename' alt='Imagen de la galería' class='gallery-image'>"
              done < file_list.txt > gallery-content.html
              echo "Archivo gallery-content.html creado."
          else
              echo "No se encontraron archivos de imagen en la carpeta 'fotos-web'."
              # Crea un archivo vacío para que la acción no falle
              touch gallery-content.html
          fi

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualizada la galería de fotos"
          file_pattern: 'gallery-content.html'
