name: Generate Gallery

on:
  push:
    branches:
      - main
    paths:
      - 'fotos-web/**'

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ¡Esta es la línea clave que faltaba!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate HTML for gallery
        id: generate
        run: |
          ls -1 fotos-web | while read filename
          do
              echo "<img src='https://raw.githubusercontent.com/${{ github.repository }}/main/fotos-web/$filename' alt='Imagen de la galería' class='gallery-image'>"
          done > gallery-content.html

      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add gallery-content.html
          git commit -m "Generated gallery content" || echo "No changes to commit"
          git push
